name: Release Go CLI

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: |
          # Extraer la versión desde el tag sin prefijo "v"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if [[ ! "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Tag '$TAG_NAME' is not a valid semantic version (X.Y.Z)." >&2
            exit 1
          fi
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "Extracted version: $TAG_NAME"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          BINARY_NAME=npu
          OUTPUT="dist/${BINARY_NAME}_${{ matrix.goos }}_${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          echo "Building binary for $GOOS/$GOARCH..."
          go build -ldflags="-s -w -X 'github.com/GNURub/node-package-updater/internal/version.Version=${{ env.VERSION }}'" -o "$OUTPUT" main.go
          echo "Binary built at $OUTPUT"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
